// Code generated by protoc-gen-goclay, but your can (must) modify it.
// source: example.proto

package example

import (
	"proto-example/internal/app/service"
	desc "proto-example/pkg/api/example"

	"github.com/utrack/clay/v2/transport"
)

type Implementation struct {
	srv *service.Service
}

// NewExampleAPI create new Implementation
func NewExampleAPI(srv *service.Service) *Implementation {
	return &Implementation{
		srv: srv,
	}
}

// GetDescription is a simple alias to the ServiceDesc constructor.
// It makes it possible to register the service implementation @ the server.
func (i *Implementation) GetDescription() transport.ServiceDesc {
	return desc.NewExampleAPIServiceDesc(i)
}
