// Code generated by protoc-gen-goclay, but your can (must) modify it.
// source: example.proto

package example

import (
	"context"
	desc "proto-example/pkg/api/example"
	"testing"

	"github.com/stretchr/testify/require"
)

func TestImplementation_GetFoo(t *testing.T) {
	api := NewExampleAPI()
	_, err := api.GetFoo(context.Background(), &desc.FooRequest{})

	require.NotNil(t, err)
	require.Equal(t, "GetFoo not implemented", err.Error())
}
