// Code generated by protoc-gen-goclay, but your can (must) modify it.
// source: example.proto

package example

import (
	"context"
	desc "proto-example/pkg/api/example"

	"github.com/pkg/errors"
)

func (i *Implementation) GetFoo(ctx context.Context, req *desc.FooRequest) (*desc.FooResponse, error) {
	return nil, errors.New("GetFoo not implemented")
}
