// Code generated by protoc-gen-goclay, but your can (must) modify it.
// source: example.proto

package example

import (
	"context"
	desc "proto-example/pkg/api/example"
)

func (i *Implementation) Health(ctx context.Context, req *desc.HealthRequest) (*desc.HealthResponse, error) {
	err := i.srv.Ping(ctx)
	return &desc.HealthResponse{
		Status: 200,
	}, err
}
