// Code generated by protoc-gen-goclay, but your can (must) modify it.
// source: example.proto

package example

import (
	"context"
	desc "proto-example/pkg/api/example"
	"testing"

	"github.com/stretchr/testify/require"
)

func TestImplementation_Health(t *testing.T) {
	api := NewExampleAPI()
	_, err := api.Health(context.Background(), &desc.HealthRequest{})

	require.NotNil(t, err)
	require.Equal(t, "Health not implemented", err.Error())
}
