// Code generated by protoc-gen-goclay, but your can (must) modify it.
// source: example.proto

package example

import (
	"context"
	desc "proto-example/pkg/api/example"

	emptypb "github.com/gogo/protobuf/types"
	"github.com/pkg/errors"
)

func (i *Implementation) PostBar(ctx context.Context, req *desc.BarRequest) (*emptypb.Empty, error) {
	return nil, errors.New("PostBar not implemented")
}
