// Code generated by protoc-gen-goclay, but your can (must) modify it.
// source: example.proto

package example

import (
	"context"
	desc "proto-example/pkg/api/example"
	"testing"

	emptypb "github.com/gogo/protobuf/types"
	"github.com/stretchr/testify/require"
)

func TestImplementation_PostBar(t *testing.T) {
	api := NewExampleAPI()
	_, err := api.PostBar(context.Background(), &desc.BarRequest{})

	require.NotNil(t, err)
	require.Equal(t, "PostBar not implemented", err.Error())
}
